# Generated by Django 4.2.4 on 2023-08-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_rename_title_land_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landinfomapping',
            old_name='like',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='landinfomapping',
            old_name='unlike',
            new_name='unlike_count',
        ),
    ]
