# Generated by Django 4.2.4 on 2023-08-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_landinfousermapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landinfousermapping',
            old_name='is_event',
            new_name='is_like_event',
        ),
    ]
