# Generated by Django 4.2.4 on 2023-08-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_rename_is_event_landinfousermapping_is_like_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='title',
            new_name='name',
        ),
    ]
